version: '3'
services:
  db:
    container_name: db-server
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
    - mysql_data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud

  app:
    container_name: app-server
    image: nextcloud:fpm
    stdin_open: true
    tty: true
    restart: always
    expose:
    - '80'
    - '9000'
    volumes:
    - app_data:/var/www/html

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    expose:
    - '80'
    - '443'
    volumes:
    - document_data:/var/www/onlyoffice/Data
    - document_log:/var/log/onlyoffice

  nginx:
    container_name: nginx-server
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - app_data:/var/www/html

  mail:
    container_name: mail-server
    image: catatnight/postfix
    ports:
    - 25:25
    environment:
    - maildomain=${maildomain}
    - smtp_user=${smtp_user}
    restart: always

volumes:
  document_data:
  document_log:
  app_data:
  mysql_data:
